### ISSUE TITLE
Permission denied in /usr/src/app

### ISSUE THREAD

**Issue by j0nm1** [renovatebot/docker-renovate#221]
Hi,
I'm using the docker image in combination with the following `.gitlab-ci.yml`:

```
run:
  variables:
    RENOVATE_TOKEN: $GITLAB_TOKEN
  image:
    name: renovate/renovate:24.38.0
    entrypoint: ['']
  script:
    - ln -sF $CI_PROJECT_DIR/config.js /usr/src/app/
    - node /usr/src/app/dist/renovate.js
  only:
    - schedules
```

This works great with `renovate/renovate:24.38.0` but starts to fail with `renovate/renovate:24.38.1` with the error: `Permission denied`

After investigating what could be the problem I found that the permissions of the `app` folder inside the `/usr/src` are different.
- 24.38.1: `drwxr-xr-x 1 root root 4096 Feb  5 15:14 app`
- 24.38.0.: `drwxrwxr-x 1 ubuntu root 4096 Feb  4 13:52 app`

I don't think this is intended but I wasn't able to find the exact commit that leads to this change.

**Comment by viceice** [comment]
Please checkout https://gitlab.com/renovate-bot/renovate-runner for official gitlab usage

```yaml
run:
  variables:
    RENOVATE_TOKEN: $GITLAB_TOKEN
  image:
    name: renovate/renovate:24.38.0
  script:
    - renovate
  only:
    - schedules
```
